baseURL = "http://nanamisawa.github.io/"
languageCode = "ja"
title = "My Blog"
theme = "hugo-nuo"


[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "About"
  weight = 20
  identifier = "about"
  url = "portfolio"

[[menu.main]]
  name = "Works"
  weight = 30
  identifier = "works"
  url = "https://github.com/laozhu"

[[menu.main]]
  name = "Tags"
  weight = 40
  identifier = "tags"
  url = "/tags/"

# Choose your social networks
email = "misawa.nana7@gmail.com"
github = "nanamisawa"
twitter = "mswn7"
