baseURL = "http://nanamisawa.github.io/"
languageCode = "ja"
title = "7."
theme = "hugo-nuo"

pygmentsUseClasses=true
pygmentsCodefences = true

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "About"
  weight = 20
  identifier = "about"
  url = "/about/"

[[menu.main]]
  name = "Papers"
  weight = 30
  identifier = "works"
  url = "https://scholar.google.co.jp/citations?user=QiscMP0AAAAJ&hl"

[[menu.main]]
  name = "Tags"
  weight = 40
  identifier = "tags"
  url = "/tags/"

[params]
  author = "Nana Misawa"
  bg = "images/grey-prism.svg"
  avatar = "images/nana_android.png"
  seotitle = "7."
  subtitle = "It's a fluke."
  description = "Hugo is one of the most popular open-source static site generators. With its amazing speed and flexibility, Hugo makes building websites fun again."
  paginate = 10
  # Choose your social networks
  email = "misawa.nana7@gmail.com"
  github = "nanamisawa"
  twitter = "mswn7"
  # Overrid theme styles in this file
  customStyle = "styles/custom.scss"
